env:
  - I_AM_ON_CI=1
rvm: 
  - 2.0.0
before_script: 
  - "cp config/database.travis.yml config/database.yml"
  - "bundle exec rake db:drop"
  - "bundle exec rake db:setup"
script: "bundle exec rake spec"
