source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'pg'
gem 'jquery-rails'
gem 'unicorn'
gem 'capistrano'
gem 'simple_form'
gem 'paper_trail'
gem 'resque', require: 'resque/server'
gem 'sorcery', github: 'releu/sorcery'
gem 'slim'
gem 'state_machine'
gem 'mailgun-rails'
gem 'fivemat'
gem 'paperclip'
gem 'yaml_db'
gem 'meta_search'
gem 'kaminari'
gem 'whenever'
gem 'redcarpet', '1.17.2'
gem 'gollum', github: 'github/gollum'
gem 'cocaine'
gem 'liquid'
gem 'rtf'
gem 'airbrake'
gem 'gravatar-ultimate'
gem 'levenshtein-ffi', require: 'levenshtein'
gem 'validates_email_format_of'
gem 'virtus'
gem 'maymay', github: 'redstonelabs/maymay'
gem 'entity', github: 'redstonelabs/entity'
gem 'rubyzip'
gem 'poltergeist', github: 'brutuscat/poltergeist'

group :test, :development do
  gem 'quiet_assets'
  gem 'spin'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'rspec-nc'
  gem 'shoulda-matchers'
  gem 'launchy'
  gem 'guard-rspec'
  gem 'guard-cucumber'
  gem 'database_cleaner'
  gem 'ci_reporter'
  gem 'therubyracer'
end

group :test do
  gem 'cucumber-rails'
end

group :assets do
  gem 'less-rails'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
