source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'pg'
gem 'jquery-rails'
gem 'unicorn'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'cancan', github: 'ryanb/cancan', branch: '2.0'
gem 'simple_form'
gem 'paper_trail'
gem 'resque', require: 'resque/server'
gem 'sorcery'
gem 'slim'
gem 'state_machine'
gem 'mailgun-rails'
gem 'redcarpet'
gem 'fivemat'
gem 'wicked_pdf'
gem 'paperclip'
gem 'therubyracer'
gem 'yaml_db'
gem 'meta_search'
gem 'kaminari'

group :test, :development do
  gem 'quiet_assets'
  gem 'spin'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'rspec-rails'
  gem 'rspec-nc'
  gem 'shoulda-matchers'
  gem 'launchy'
  gem 'guard-rspec'
  gem 'database_cleaner'
end

group :assets do
  gem 'less-rails'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
