accounts:
  - manage
clusters:
  - manage
cluster_fields:
  - manage
critical_technologies:
  - manage
credentials:
  - manage
direction_of_sciences:
  - manage
extends:
  - manage
groups:
  - manage
history_items:
  - access
images:
  - manage
import_items:
  - manage
organizations:
  - manage
organization_kinds:
  - manage
position_names:
  - manage
projects:
  - manage
project_prefixes:
  - manage
requests:
  - manage
settings:
  - manage
sureties:
  - manage
  - confirm
  - unconfirm
  - activate
  - close
  - decline
tasks:
  - manage
tickets:
  - manage
ticket_fields:
  - manage
ticket_questions:
  - manage
ticket_tags:
  - manage
ticket_templates:
  - manage
users:
  - manage
pages:
  - manage
  - show_all
all:
  - show_all
reports:
  - manage
  - review
  - access
  - supervise
  - admin
sessions:
  - manage
admin:
  - access
user_surveys:
  - access
research_areas:
  - manage
faults:
  - resolve
console:
  - access
