development:
  adapter: postgresql
  database: octoshell_developement
  username: octoshell
  pool: 5

test:
  adapter: postgresql
  database: octoshell_test
  username: octoshell
  pool: 5

production:
  adapter: postgresql
  database: octoshell_developement
  username: octoshell
  pool: 5
