---
ru:
  layouts:
    application:
      help: ! '<span class="translation_missing" title="translation missing: ru.layouts.application.help">Help</span>'
      sign_out: Выход
  shared:
    admin_menu:
      accesses: Публичные ключи на кластере
      cluster_projects: Проекты на кластере
      cluster_users: Пользователи на кластере
      clusters: Кластеры
      critical_technologies: Critical Technologies
      direction_of_sciences: Direction of Science
      extends: Расширения
      groups: Группы
      images: Изображения
      import: Импорт
      more: Еще
      organization_kinds: Типы организаций
      organizations: Организации
      position_names: Должности
      project_prefixes: Префиксы проектов
      projects: Проекты
      requests: Заявки
      sureties: Поручительства
      tasks: Процедуры
      users: Пользователи
    top_menu:
      admin: Admin
      dashboard: Dashboard
      notifications: Notifications (4)
