---
ru:
  admin:
    memberships:
      table:
        no_memberships: There is no memberships
    requests:
      table:
        open: ! '<span class="translation_missing" title="translation missing: ru.admin.requests.table.open">Open</span>'
  layouts:
    application:
      help: ! '<span class="translation_missing" title="translation missing: ru.layouts.application.help">Help</span>'
      sign_out: Выход
  notifications:
    index:
      new_ticket: Ask support
      support: Support
      title: Notifications
  projects:
    index:
      new_project: Новый проект
      title: Проекты
      use_code: Использовать код приглашения
    table:
      no_projects: There are no Projects
  shared:
    admin_menu:
      accesses: Публичные ключи на кластере
      cluster_projects: Проекты на кластере
      cluster_users: Пользователи на кластере
      clusters: Кластеры
      critical_technologies: Critical Technologies
      direction_of_sciences: Direction of Science
      extends: Расширения
      groups: Группы
      images: Изображения
      import: Импорт
      more: Еще
      organization_kinds: Типы организаций
      organizations: Организации
      position_names: Должности
      project_prefixes: Префиксы проектов
      projects: Проекты
      requests: Заявки
      sureties: Поручительства
      tasks: Процедуры
      users: Пользователи
    dashboard_menu:
      clusters: Кластеры
      pages: Справка
      profile: Профиль
      projects: Проекты
      requests: Заявки
      tickets: Поддержка
    top_menu:
      admin: Admin
      dashboard: Dashboard
      notifications: Notifications (4)
