class CleanupReportProjects < ActiveRecord::Migration
  def change
    change_table :report_projects do |t|
      t.remove "ru_title"
      t.remove "ru_author"
      t.remove "ru_email"
      t.remove "ru_driver"
      t.remove "ru_strategy"
      t.remove "ru_objective"
      t.remove "ru_impact"
      t.remove "ru_usage"
      t.remove "ru_lang"
      t.remove "en_title"
      t.remove "en_author"
      t.remove "en_email"
      t.remove "en_driver"
      t.remove "en_strategy"
      t.remove "en_objective"
      t.remove "en_impact"
      t.remove "en_usage"
      t.remove "en_lang"
      t.remove "books_count"
      t.remove "vacs_count"
      t.remove "lectures_count"
      t.remove "international_conferences_count"
      t.remove "russian_conferences_count"
      t.remove "doctors_dissertations_count"
      t.remove "candidates_dissertations_count"
      t.remove "students_count"
      t.remove "rffi_grants_count"
      t.remove "ministry_of_defence_grants_count"
      t.remove "ros_nano_tech_grants_count"
      t.remove "ministry_of_communications_grants_count"
      t.remove "ran_grants_count"
      t.remove "other_russian_grants_count"
      t.remove "other_intenational_grants_count"
      t.remove "awards_count"
      t.remove "award_names"
      t.remove "additional"
      t.remove "hours"
      t.remove "size"
      t.remove "full_power"
      t.remove "strict_schedule"
      t.remove "comment"
      t.remove "areas"
      t.remove "directions_of_science"
      t.remove "critical_technologies"
      t.remove "computing_systems"
      t.remove "lomonosov_logins"
      t.remove "chebyshev_logins"
      t.remove "materials_file_name"
      t.remove "materials_content_type"
      t.remove "materials_file_size"
      t.remove "materials_updated_at"
      t.remove "your_students_count"
      t.remove "graduates_count"
      t.remove "ministry_of_education_grants_count"
      t.remove "rosnano_grants_count"

      t.text :ru_title
      t.text :ru_author
      t.text :ru_email
      t.text :ru_driver
      t.text :ru_strategy
      t.text :ru_objective
      t.text :ru_impact
      t.text :ru_usage
      t.text :en_title
      t.text :en_author
      t.text :en_email
      t.text :en_driver
      t.text :en_strategy
      t.text :en_objective
      t.text :en_impact
      t.text :en_usage
      t.text :directions_of_science
      t.text :critical_technologies
      t.text :areas
      t.text :computing_systems
      t.text :lomonosov_logins
      t.text :chebyshev_logins
      t.attachment :materials
      t.integer :books_count
      t.integer :vacs_count
      t.integer :lectures_count
      t.integer :international_conferences_count
      t.integer :russian_conferences_count
      t.integer :doctors_dissertations_count
      t.integer :candidates_dissertations_count
      t.integer :students_count
      t.integer :graduates_count
      t.integer :your_students_count
      t.integer :rffi_grants_count
      t.integer :ministry_of_education_grants_count
      t.integer :rosnano_grants_count
      t.integer :ministry_of_communications_grants_count
      t.integer :ministry_of_defence_grants_count
      t.integer :ran_grants_count
      t.integer :other_russian_grants_count
      t.integer :other_intenational_grants_count
      t.text :award_names
      t.integer :lomonosov_intel_hours
      t.integer :lomonosov_nvidia_hours
      t.integer :chebyshev_hours
      t.integer :lomonosov_size
      t.integer :chebyshev_size
      t.text :exclusive_usage
      t.text :strict_schedule
      t.boolean :wanna_speak
      t.text :request_comment
    end
  end
end
